version: '3.8'

services:
  customer-db:
    image: mysql:8.0
    container_name: customer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - customer-network

  customer-app:
    image: customer-app
    container_name: customer-app
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:root@customer-db:3306/customer_db
    ports:
      - "5000:5000"
    depends_on:
      - customer-db
    volumes:
      - .:/app
    networks:
      - customer-network
    restart: always
    

volumes:
  mysql_data:

networks:
  customer-network:
    driver: bridge
