name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push customer-db image
        uses: docker/build-push-action@v5
        with:
          context: ./customer_db_dockerfile  # Path to the directory with Dockerfile for customer-db
          file: ./customer_db_dockerfile/Dockerfile  # Dockerfile for customer-db
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/customer-db:latest

      - name: Build and push customer-app image
        uses: docker/build-push-action@v5
        with:
          context: .  # Path to your customer-app Dockerfile
          file: ./dockerfile  # Dockerfile for customer-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/customer-app:latest

      - name: Deploy using Docker Compose
        run: |

          docker-compose up
        env:
          DOCKER_BUILDKIT: 1
